### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by malsatin** [Serubin/Dynamic-Motd#1]
Hi.
As for debian 9 there should be some changes in script
in sysinfo
```
ip=`/sbin/ifconfig ens3 | awk -F"[: ]+" '/inet /{print $3}'`
```
And for updates to work we have to install `apt-get install python-apt`

**Comment by Serubin** [comment]
That's good to know. Would you mind opening a merge request, otherwise I'll get to it in the next few weeks? I don't have any machines on debian 9 yet.

I'll likely just add python-apt to the dependency list.

Thanks for bringing this to my attention.

**Comment by Serubin** [comment]
I looked into this issue further and I've found two issues
1) you are using a different interface naming convention than ethX
2) `addr` is not explicitly required output in `ifconfig` anymore which is what I believe what you were pointing out.

I'll update accordingly with a few other updates.

**Comment by malsatin** [comment]
It's Debian 9 convention to use `ensX` instead of `ethX`. You new solution won't work with system that have more than one IPv4 adapter.
IMHO you can leave `eth0` as a default variant, but make somewhere a note that some systems can have different adapter as a default one.

And you didn't add `python-apt` to dependency list

**Comment by Serubin** [comment]
The new solution doesn't care what naming convention you use nor what version of debian you are using. I'm still testing a few items and will update the README when I've completed this.
